
SOURCES += ../cocos2d-x/cocos2dx/actions/CCAction.cpp \
../cocos2d-x/cocos2dx/actions/CCActionCamera.cpp \
../cocos2d-x/cocos2dx/actions/CCActionCatmullRom.cpp \
../cocos2d-x/cocos2dx/actions/CCActionEase.cpp \
../cocos2d-x/cocos2dx/actions/CCActionGrid.cpp \
../cocos2d-x/cocos2dx/actions/CCActionGrid3D.cpp \
../cocos2d-x/cocos2dx/actions/CCActionInstant.cpp \
../cocos2d-x/cocos2dx/actions/CCActionInterval.cpp \
../cocos2d-x/cocos2dx/actions/CCActionManager.cpp \
../cocos2d-x/cocos2dx/actions/CCActionPageTurn3D.cpp \
../cocos2d-x/cocos2dx/actions/CCActionProgressTimer.cpp \
../cocos2d-x/cocos2dx/actions/CCActionTiledGrid.cpp \
../cocos2d-x/cocos2dx/actions/CCActionTween.cpp \
../cocos2d-x/cocos2dx/actions/CCLinkPosition.cpp \
../cocos2d-x/cocos2dx/base_nodes/CCAtlasNode.cpp \
../cocos2d-x/cocos2dx/base_nodes/CCGLBufferedNode.cpp \
../cocos2d-x/cocos2dx/base_nodes/CCNode.cpp \
../cocos2d-x/cocos2dx/CCCamera.cpp \
../cocos2d-x/cocos2dx/CCConfiguration.cpp \
../cocos2d-x/cocos2dx/CCDirector.cpp \
../cocos2d-x/cocos2dx/ccFPSImages.c \
../cocos2d-x/cocos2dx/CCScheduler.cpp \
../cocos2d-x/cocos2dx/cocoa/CCAffineTransform.cpp \
../cocos2d-x/cocos2dx/cocoa/CCArray.cpp \
../cocos2d-x/cocos2dx/cocoa/CCAutoreleasePool.cpp \
../cocos2d-x/cocos2dx/cocoa/CCDataVisitor.cpp \
../cocos2d-x/cocos2dx/cocoa/CCDictionary.cpp \
../cocos2d-x/cocos2dx/cocoa/CCGeometry.cpp \
../cocos2d-x/cocos2dx/cocoa/CCNS.cpp \
../cocos2d-x/cocos2dx/cocoa/CCObject.cpp \
../cocos2d-x/cocos2dx/cocoa/CCPointArray.cpp \
../cocos2d-x/cocos2dx/cocoa/CCSet.cpp \
../cocos2d-x/cocos2dx/cocoa/CCString.cpp \
../cocos2d-x/cocos2dx/cocoa/CCZone.cpp \
../cocos2d-x/cocos2dx/cocos2d.cpp \
../cocos2d-x/cocos2dx/draw_nodes/CCDrawingPrimitives.cpp \
../cocos2d-x/cocos2dx/draw_nodes/CCDrawNode.cpp \
../cocos2d-x/cocos2dx/draw_nodes/CCShapeNode.cpp \
../cocos2d-x/cocos2dx/effects/CCGrabber.cpp \
../cocos2d-x/cocos2dx/effects/CCGrid.cpp \
../cocos2d-x/cocos2dx/kazmath/src/aabb.c \
../cocos2d-x/cocos2dx/kazmath/src/GL/mat4stack.c \
../cocos2d-x/cocos2dx/kazmath/src/GL/matrix.c \
../cocos2d-x/cocos2dx/kazmath/src/mat3.c \
../cocos2d-x/cocos2dx/kazmath/src/mat4.c \
../cocos2d-x/cocos2dx/kazmath/src/plane.c \
../cocos2d-x/cocos2dx/kazmath/src/quaternion.c \
../cocos2d-x/cocos2dx/kazmath/src/ray2.c \
../cocos2d-x/cocos2dx/kazmath/src/utility.c \
../cocos2d-x/cocos2dx/kazmath/src/vec2.c \
../cocos2d-x/cocos2dx/kazmath/src/vec3.c \
../cocos2d-x/cocos2dx/kazmath/src/vec4.c \
../cocos2d-x/cocos2dx/keypad_dispatcher/CCKeypadDelegate.cpp \
../cocos2d-x/cocos2dx/keypad_dispatcher/CCKeypadDispatcher.cpp \
../cocos2d-x/cocos2dx/label_nodes/CCLabelAtlas.cpp \
../cocos2d-x/cocos2dx/label_nodes/CCLabelBMFont.cpp \
../cocos2d-x/cocos2dx/label_nodes/CCLabelTTF.cpp \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCLayer.cpp \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCScene.cpp \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCTransition.cpp \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCTransitionPageTurn.cpp \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCTransitionProgress.cpp \
../cocos2d-x/cocos2dx/menu_nodes/CCMenu.cpp \
../cocos2d-x/cocos2dx/menu_nodes/CCMenuItem.cpp \
../cocos2d-x/cocos2dx/misc_nodes/CCClippingNode.cpp \
../cocos2d-x/cocos2dx/misc_nodes/CCClippingRegionNode.cpp \
../cocos2d-x/cocos2dx/misc_nodes/CCMotionStreak.cpp \
../cocos2d-x/cocos2dx/misc_nodes/CCProgressTimer.cpp \
../cocos2d-x/cocos2dx/misc_nodes/CCRenderTexture.cpp \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleBatchNode.cpp \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleExamples.cpp \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleSystem.cpp \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleSystemQuad.cpp \
../cocos2d-x/cocos2dx/platform/CCEGLViewProtocol.cpp \
../cocos2d-x/cocos2dx/platform/CCFileUtils.cpp \
../cocos2d-x/cocos2dx/platform/CCImageCommonWebp.cpp \
../cocos2d-x/cocos2dx/platform/CCSAXParser.cpp \
../cocos2d-x/cocos2dx/platform/CCThread.cpp \
../cocos2d-x/cocos2dx/platform/CCZipFile.cpp \
../cocos2d-x/cocos2dx/platform/platform.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCAccelerometer.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCApplication.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCCommon.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCEGLView.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCFileUtilsQt.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCGLWidget.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCImage.cpp \
../cocos2d-x/cocos2dx/platform/qt/CCStdC.cpp \
../cocos2d-x/cocos2dx/script_support/CCScriptSupport.cpp \
../cocos2d-x/cocos2dx/shaders/CCGLProgram.cpp \
../cocos2d-x/cocos2dx/shaders/ccGLStateCache.cpp \
../cocos2d-x/cocos2dx/shaders/CCShaderCache.cpp \
../cocos2d-x/cocos2dx/shaders/ccShaders.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCAnimation.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCAnimationCache.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCGraySprite.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCSprite.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCSpriteBatchNode.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCSpriteFrame.cpp \
../cocos2d-x/cocos2dx/sprite_nodes/CCSpriteFrameCache.cpp \
../cocos2d-x/cocos2dx/support/base64.cpp \
../cocos2d-x/cocos2dx/support/CCNotificationCenter.cpp \
../cocos2d-x/cocos2dx/support/CCPointExtension.cpp \
../cocos2d-x/cocos2dx/support/CCProfiling.cpp \
../cocos2d-x/cocos2dx/support/ccUTF8.cpp \
../cocos2d-x/cocos2dx/support/ccUtils.cpp \
../cocos2d-x/cocos2dx/support/CCVertex.cpp \
../cocos2d-x/cocos2dx/support/component/CCComponent.cpp \
../cocos2d-x/cocos2dx/support/component/CCComponentContainer.cpp \
../cocos2d-x/cocos2dx/support/data_support/ccCArray.cpp \
../cocos2d-x/cocos2dx/support/image_support/TGAlib.cpp \
../cocos2d-x/cocos2dx/support/tinyxml2/tinyxml2.cpp \
../cocos2d-x/cocos2dx/support/TransformUtils.cpp \
../cocos2d-x/cocos2dx/support/user_default/CCUserDefault.cpp \
../cocos2d-x/cocos2dx/support/zip_support/ioapi.cpp \
../cocos2d-x/cocos2dx/support/zip_support/unzip.cpp \
../cocos2d-x/cocos2dx/support/zip_support/ZipUtils.cpp \
../cocos2d-x/cocos2dx/text_input_node/CCIMEDispatcher.cpp \
../cocos2d-x/cocos2dx/text_input_node/CCTextFieldTTF.cpp \
../cocos2d-x/cocos2dx/textures/CCTexture2D.cpp \
../cocos2d-x/cocos2dx/textures/CCTextureAtlas.cpp \
../cocos2d-x/cocos2dx/textures/CCTextureCache.cpp \
../cocos2d-x/cocos2dx/textures/CCTextureETC.cpp \
../cocos2d-x/cocos2dx/textures/CCTexturePVR.cpp \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCParallaxNode.cpp \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTileMapAtlas.cpp \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXLayer.cpp \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXObjectGroup.cpp \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXTiledMap.cpp \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXXMLParser.cpp \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouch.cpp \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouchDispatcher.cpp \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouchHandler.cpp


HEADERS += \
../cocos2d-x/cocos2dx/actions/CCAction.h \
../cocos2d-x/cocos2dx/actions/CCActionCamera.h \
../cocos2d-x/cocos2dx/actions/CCActionCatmullRom.h \
../cocos2d-x/cocos2dx/actions/CCActionEase.h \
../cocos2d-x/cocos2dx/actions/CCActionGrid.h \
../cocos2d-x/cocos2dx/actions/CCActionGrid3D.h \
../cocos2d-x/cocos2dx/actions/CCActionInstant.h \
../cocos2d-x/cocos2dx/actions/CCActionInterval.h \
../cocos2d-x/cocos2dx/actions/CCActionManager.h \
../cocos2d-x/cocos2dx/actions/CCActionPageTurn3D.h \
../cocos2d-x/cocos2dx/actions/CCActionProgressTimer.h \
../cocos2d-x/cocos2dx/actions/CCActionTiledGrid.h \
../cocos2d-x/cocos2dx/actions/CCActionTween.h \
../cocos2d-x/cocos2dx/actions/CCLinkPosition.h \
../cocos2d-x/cocos2dx/base_nodes/CCAtlasNode.h \
../cocos2d-x/cocos2dx/base_nodes/CCGLBufferedNode.h \
../cocos2d-x/cocos2dx/base_nodes/CCNode.h \
../cocos2d-x/cocos2dx/CCCamera.h \
../cocos2d-x/cocos2dx/CCConfiguration.h \
../cocos2d-x/cocos2dx/CCDirector.h \
../cocos2d-x/cocos2dx/ccFPSImages.h \
../cocos2d-x/cocos2dx/CCScheduler.h \
../cocos2d-x/cocos2dx/cocoa/CCAffineTransform.h \
../cocos2d-x/cocos2dx/cocoa/CCArray.h \
../cocos2d-x/cocos2dx/cocoa/CCAutoreleasePool.h \
../cocos2d-x/cocos2dx/cocoa/CCBool.h \
../cocos2d-x/cocos2dx/cocoa/CCDataVisitor.h \
../cocos2d-x/cocos2dx/cocoa/CCDictionary.h \
../cocos2d-x/cocos2dx/cocoa/CCDouble.h \
../cocos2d-x/cocos2dx/cocoa/CCFloat.h \
../cocos2d-x/cocos2dx/cocoa/CCGeometry.h \
../cocos2d-x/cocos2dx/cocoa/CCInteger.h \
../cocos2d-x/cocos2dx/cocoa/CCNS.h \
../cocos2d-x/cocos2dx/cocoa/CCObject.h \
../cocos2d-x/cocos2dx/cocoa/CCPointArray.h \
../cocos2d-x/cocos2dx/cocoa/CCSet.h \
../cocos2d-x/cocos2dx/cocoa/CCString.h \
../cocos2d-x/cocos2dx/cocoa/CCZone.h \
../cocos2d-x/cocos2dx/draw_nodes/CCDrawingPrimitives.h \
../cocos2d-x/cocos2dx/draw_nodes/CCDrawNode.h \
../cocos2d-x/cocos2dx/draw_nodes/CCShapeNode.h \
../cocos2d-x/cocos2dx/effects/CCGrabber.h \
../cocos2d-x/cocos2dx/effects/CCGrid.h \
../cocos2d-x/cocos2dx/include/ccConfig.h \
../cocos2d-x/cocos2dx/include/CCEventType.h \
../cocos2d-x/cocos2dx/include/ccMacros.h \
../cocos2d-x/cocos2dx/include/CCProtocols.h \
../cocos2d-x/cocos2dx/include/ccTypeInfo.h \
../cocos2d-x/cocos2dx/include/ccTypes.h \
../cocos2d-x/cocos2dx/include/cocos2d.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/aabb.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/GL/mat4stack.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/GL/matrix.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/kazmath.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/mat3.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/mat4.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/plane.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/quaternion.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/ray2.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/utility.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/vec2.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/vec3.h \
../cocos2d-x/cocos2dx/kazmath/include/kazmath/vec4.h \
../cocos2d-x/cocos2dx/keypad_dispatcher/CCKeypadDelegate.h \
../cocos2d-x/cocos2dx/keypad_dispatcher/CCKeypadDispatcher.h \
../cocos2d-x/cocos2dx/label_nodes/CCLabelAtlas.h \
../cocos2d-x/cocos2dx/label_nodes/CCLabelBMFont.h \
../cocos2d-x/cocos2dx/label_nodes/CCLabelTTF.h \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCLayer.h \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCScene.h \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCTransition.h \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCTransitionPageTurn.h \
../cocos2d-x/cocos2dx/layers_scenes_transitions_nodes/CCTransitionProgress.h \
../cocos2d-x/cocos2dx/menu_nodes/CCMenu.h \
../cocos2d-x/cocos2dx/menu_nodes/CCMenuItem.h \
../cocos2d-x/cocos2dx/misc_nodes/CCClippingNode.h \
../cocos2d-x/cocos2dx/misc_nodes/CCClippingRegionNode.h \
../cocos2d-x/cocos2dx/misc_nodes/CCMotionStreak.h \
../cocos2d-x/cocos2dx/misc_nodes/CCProgressTimer.h \
../cocos2d-x/cocos2dx/misc_nodes/CCRenderTexture.h \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleBatchNode.h \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleExamples.h \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleSystem.h \
../cocos2d-x/cocos2dx/particle_nodes/CCParticleSystemQuad.h \
../cocos2d-x/cocos2dx/particle_nodes/firePngData.h \
../cocos2d-x/cocos2dx/platform/CCAccelerometerDelegate.h \
../cocos2d-x/cocos2dx/platform/CCApplicationProtocol.h \
../cocos2d-x/cocos2dx/platform/CCCommon.h \
../cocos2d-x/cocos2dx/platform/CCDevice.h \
../cocos2d-x/cocos2dx/platform/CCEGLViewProtocol.h \
../cocos2d-x/cocos2dx/platform/CCFileUtils.h \
../cocos2d-x/cocos2dx/platform/CCImage.h \
../cocos2d-x/cocos2dx/platform/CCImageCommon_cpp.h \
../cocos2d-x/cocos2dx/platform/CCPlatformConfig.h \
../cocos2d-x/cocos2dx/platform/CCPlatformMacros.h \
../cocos2d-x/cocos2dx/platform/CCSAXParser.h \
../cocos2d-x/cocos2dx/platform/CCThread.h \
../cocos2d-x/cocos2dx/platform/CCZipFile.h \
../cocos2d-x/cocos2dx/platform/platform.h \
../cocos2d-x/cocos2dx/platform/qt/CCAccelerometer.h \
../cocos2d-x/cocos2dx/platform/qt/CCApplication.h \
../cocos2d-x/cocos2dx/platform/qt/CCEGLView.h \
../cocos2d-x/cocos2dx/platform/qt/CCFileUtilsQt.h \
../cocos2d-x/cocos2dx/platform/qt/CCGL.h \
../cocos2d-x/cocos2dx/platform/qt/CCGLWidget.h \
../cocos2d-x/cocos2dx/platform/qt/CCPlatformDefine.h \
../cocos2d-x/cocos2dx/platform/qt/CCStdC.h \
../cocos2d-x/cocos2dx/platform/qt/compat/stdint.h \
../cocos2d-x/cocos2dx/script_support/CCScriptSupport.h \
../cocos2d-x/cocos2dx/shaders/CCGLProgram.h \
../cocos2d-x/cocos2dx/shaders/ccGLStateCache.h \
../cocos2d-x/cocos2dx/shaders/ccShader_Position_uColor_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_Position_uColor_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionColor_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionColor_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionColorLengthTexture_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionColorLengthTexture_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTexture_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTexture_uColor_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTexture_uColor_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTexture_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTextureA8Color_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTextureA8Color_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTextureColor_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTextureColor_vert.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTextureColorAlphaTest_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShader_PositionTextureGray_frag.h \
../cocos2d-x/cocos2dx/shaders/CCShaderCache.h \
../cocos2d-x/cocos2dx/shaders/ccShaderEx_SwitchMask_frag.h \
../cocos2d-x/cocos2dx/shaders/ccShaders.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCAnimation.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCAnimationCache.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCGraySprite.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCSprite.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCSpriteBatchNode.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCSpriteFrame.h \
../cocos2d-x/cocos2dx/sprite_nodes/CCSpriteFrameCache.h \
../cocos2d-x/cocos2dx/support/base64.h \
../cocos2d-x/cocos2dx/support/CCNotificationCenter.h \
../cocos2d-x/cocos2dx/support/CCPointExtension.h \
../cocos2d-x/cocos2dx/support/CCProfiling.h \
../cocos2d-x/cocos2dx/support/ccUTF8.h \
../cocos2d-x/cocos2dx/support/ccUtils.h \
../cocos2d-x/cocos2dx/support/CCVertex.h \
../cocos2d-x/cocos2dx/support/component/CCComponent.h \
../cocos2d-x/cocos2dx/support/component/CCComponentContainer.h \
../cocos2d-x/cocos2dx/support/data_support/ccCArray.h \
../cocos2d-x/cocos2dx/support/data_support/uthash.h \
../cocos2d-x/cocos2dx/support/data_support/utlist.h \
../cocos2d-x/cocos2dx/support/image_support/TGAlib.h \
../cocos2d-x/cocos2dx/support/tinyxml2/tinyxml2.h \
../cocos2d-x/cocos2dx/support/TransformUtils.h \
../cocos2d-x/cocos2dx/support/user_default/CCUserDefault.h \
../cocos2d-x/cocos2dx/support/zip_support/ioapi.h \
../cocos2d-x/cocos2dx/support/zip_support/unzip.h \
../cocos2d-x/cocos2dx/support/zip_support/ZipUtils.h \
../cocos2d-x/cocos2dx/text_input_node/CCIMEDelegate.h \
../cocos2d-x/cocos2dx/text_input_node/CCIMEDispatcher.h \
../cocos2d-x/cocos2dx/text_input_node/CCTextFieldTTF.h \
../cocos2d-x/cocos2dx/textures/CCTexture2D.h \
../cocos2d-x/cocos2dx/textures/CCTextureAtlas.h \
../cocos2d-x/cocos2dx/textures/CCTextureCache.h \
../cocos2d-x/cocos2dx/textures/CCTextureETC.h \
../cocos2d-x/cocos2dx/textures/CCTexturePVR.h \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCParallaxNode.h \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTileMapAtlas.h \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXLayer.h \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXObjectGroup.h \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXTiledMap.h \
../cocos2d-x/cocos2dx/tilemap_parallax_nodes/CCTMXXMLParser.h \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouch.h \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouchDelegateProtocol.h \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouchDispatcher.h \
../cocos2d-x/cocos2dx/touch_dispatcher/CCTouchHandler.h

INCLUDEPATH += ../cocos2d-x/cocos2dx \
../cocos2d-x/cocos2dx/include \
../cocos2d-x/cocos2dx/platform \
../cocos2d-x/cocos2dx/platform/qt \
../cocos2d-x/cocos2dx/kazmath/include
