
SOURCES += \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsBody.cpp \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsDebugNode.cpp \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsShape.cpp \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsSupport.cpp \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsWorld.cpp \
../cocos2d-x/external/chipmunk/luabinding/CCPhysicsWorld_luabinding.cpp \
../cocos2d-x/external/chipmunk/src/chipmunk.c \
../cocos2d-x/external/chipmunk/src/constraints/cpConstraint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpDampedRotarySpring.c \
../cocos2d-x/external/chipmunk/src/constraints/cpDampedSpring.c \
../cocos2d-x/external/chipmunk/src/constraints/cpGearJoint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpGrooveJoint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpPinJoint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpPivotJoint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpRatchetJoint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpRotaryLimitJoint.c \
../cocos2d-x/external/chipmunk/src/constraints/cpSimpleMotor.c \
../cocos2d-x/external/chipmunk/src/constraints/cpSlideJoint.c \
../cocos2d-x/external/chipmunk/src/cpArbiter.c \
../cocos2d-x/external/chipmunk/src/cpArray.c \
../cocos2d-x/external/chipmunk/src/cpBB.c \
../cocos2d-x/external/chipmunk/src/cpBBTree.c \
../cocos2d-x/external/chipmunk/src/cpBody.c \
../cocos2d-x/external/chipmunk/src/cpCollision.c \
../cocos2d-x/external/chipmunk/src/cpHashSet.c \
../cocos2d-x/external/chipmunk/src/cpPolyShape.c \
../cocos2d-x/external/chipmunk/src/cpShape.c \
../cocos2d-x/external/chipmunk/src/cpSpace.c \
../cocos2d-x/external/chipmunk/src/cpSpaceComponent.c \
../cocos2d-x/external/chipmunk/src/cpSpaceHash.c \
../cocos2d-x/external/chipmunk/src/cpSpaceQuery.c \
../cocos2d-x/external/chipmunk/src/cpSpaceStep.c \
../cocos2d-x/external/chipmunk/src/cpSpatialIndex.c \
../cocos2d-x/external/chipmunk/src/cpSweep1D.c \
../cocos2d-x/external/chipmunk/src/cpVect.c \
../cocos2d-x/external/extra/crypto/base64/libb64.c \
../cocos2d-x/external/extra/crypto/CCCrypto.cpp \
../cocos2d-x/external/extra/crypto/md5/md5.c \
../cocos2d-x/external/extra/crypto/xxtea/xxtea.c \
../cocos2d-x/external/extra/luabinding/cocos2dx_extra_ios_iap_luabinding.cpp \
../cocos2d-x/external/extra/luabinding/cocos2dx_extra_luabinding.cpp \
../cocos2d-x/external/extra/network/CCHTTPRequest.cpp \
../cocos2d-x/external/extra/network/CCNetwork.cpp \
../cocos2d-x/external/extra/platform/android/CCCryptoAndroid.cpp \
../cocos2d-x/external/extra/platform/android/CCNativeAndroid.cpp \
../cocos2d-x/external/extra/platform/android/CCNetworkAndroid.cpp \
../cocos2d-x/external/extra/platform/win32/CCCryptoWin32.cpp \
../cocos2d-x/external/extra/platform/win32/CCNative.cpp \
../cocos2d-x/external/extra/platform/win32/CCNativeWin32.cpp \
../cocos2d-x/external/extra/platform/win32/CCNetworkWin32.cpp \
../cocos2d-x/external/extra/store/CCStorePaymentTransaction.cpp \
../cocos2d-x/external/extra/store/CCStoreProduct.cpp \
../cocos2d-x/external/luaproxy/LuaEventHandler.cpp \
../cocos2d-x/external/luaproxy/tolua/luaopen_LuaProxy.cpp \
../cocos2d-x/external/luaproxy/ui/CursorTextField.cpp \
../cocos2d-x/external/luaproxy/ui/UIUtil.cpp


HEADERS += \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsBody.h \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsDebugNode.h \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsShape.h \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsSupport.h \
../cocos2d-x/external/chipmunk/cocos2dx_support/CCPhysicsWorld.h \
../cocos2d-x/external/chipmunk/include/chipmunk.h \
../cocos2d-x/external/chipmunk/include/chipmunk_ffi.h \
../cocos2d-x/external/chipmunk/include/chipmunk_private.h \
../cocos2d-x/external/chipmunk/include/chipmunk_types.h \
../cocos2d-x/external/chipmunk/include/chipmunk_unsafe.h \
../cocos2d-x/external/chipmunk/include/constraints/cpConstraint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpDampedRotarySpring.h \
../cocos2d-x/external/chipmunk/include/constraints/cpDampedSpring.h \
../cocos2d-x/external/chipmunk/include/constraints/cpGearJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpGrooveJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpPinJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpPivotJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpRatchetJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpRotaryLimitJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/cpSimpleMotor.h \
../cocos2d-x/external/chipmunk/include/constraints/cpSlideJoint.h \
../cocos2d-x/external/chipmunk/include/constraints/util.h \
../cocos2d-x/external/chipmunk/include/cpArbiter.h \
../cocos2d-x/external/chipmunk/include/cpBB.h \
../cocos2d-x/external/chipmunk/include/cpBody.h \
../cocos2d-x/external/chipmunk/include/cpPolyShape.h \
../cocos2d-x/external/chipmunk/include/cpShape.h \
../cocos2d-x/external/chipmunk/include/cpSpace.h \
../cocos2d-x/external/chipmunk/include/cpSpatialIndex.h \
../cocos2d-x/external/chipmunk/include/cpVect.h \
../cocos2d-x/external/chipmunk/luabinding/CCPhysicsWorld_luabinding.h \
../cocos2d-x/external/chipmunk/src/prime.h \
../cocos2d-x/external/extra/cocos2dx_extra.h \
../cocos2d-x/external/extra/crypto/base64/libb64.h \
../cocos2d-x/external/extra/crypto/CCCrypto.h \
../cocos2d-x/external/extra/crypto/md5/md5.h \
../cocos2d-x/external/extra/crypto/xxtea/xxtea.h \
../cocos2d-x/external/extra/luabinding/cocos2dx_extra_ios_iap_luabinding.h \
../cocos2d-x/external/extra/luabinding/cocos2dx_extra_luabinding.h \
../cocos2d-x/external/extra/native/CCAlertViewDelegate.h \
../cocos2d-x/external/extra/native/CCNative.h \
../cocos2d-x/external/extra/network/CCHTTPRequest.h \
../cocos2d-x/external/extra/network/CCHTTPRequestDelegate.h \
../cocos2d-x/external/extra/network/CCNetwork.h \
../cocos2d-x/external/extra/platform/ios/CCNativeIOS.h \
../cocos2d-x/external/extra/platform/ios/CCStoreIOS.h \
../cocos2d-x/external/extra/platform/ios/CCStoreReceiptVerifyRequestIOS.h \
../cocos2d-x/external/extra/platform/ios/json/SBJSON.h \
../cocos2d-x/external/extra/platform/ios/json/SBJsonBase.h \
../cocos2d-x/external/extra/platform/ios/json/SBJsonParser.h \
../cocos2d-x/external/extra/platform/ios/json/SBJsonWriter.h \
../cocos2d-x/external/extra/platform/ios/openudid/OpenUDIDIOS.h \
../cocos2d-x/external/extra/platform/ios_mac/ReachabilityIOSMac.h \
../cocos2d-x/external/extra/platform/mac/CCNativeMac.h \
../cocos2d-x/external/extra/platform/mac/openudid/OpenUDIDMac.h \
../cocos2d-x/external/extra/platform/win32/CCNativeWin32.h \
../cocos2d-x/external/extra/platform/win32/CCNativeWin32def.h \
../cocos2d-x/external/extra/store/CCStore.h \
../cocos2d-x/external/extra/store/CCStorePaymentTransaction.h \
../cocos2d-x/external/extra/store/CCStorePaymentTransactionWrapper.h \
../cocos2d-x/external/extra/store/CCStoreProduct.h \
../cocos2d-x/external/extra/store/CCStoreProductsRequestDelegate.h \
../cocos2d-x/external/extra/store/CCStoreTransactionObserver.h \
../cocos2d-x/external/libwebsockets/android/include/libwebsockets.h \
../cocos2d-x/external/libwebsockets/ios/include/libwebsockets.h \
../cocos2d-x/external/libwebsockets/mac/include/libwebsockets.h \
../cocos2d-x/external/libwebsockets/win32/include/libwebsockets.h \
../cocos2d-x/external/libwebsockets/win32/include/win32helpers/gettimeofday.h \
../cocos2d-x/external/libwebsockets/win32/include/win32helpers/websock-w32.h \
../cocos2d-x/external/luaproxy/LuaEventHandler.hpp \
../cocos2d-x/external/luaproxy/LuaProxy.hpp \
../cocos2d-x/external/luaproxy/LuaTableView.hpp \
../cocos2d-x/external/luaproxy/tolua/luaopen_LuaProxy.h \
../cocos2d-x/external/luaproxy/tolua/tolua_CCBAnimationManager.h \
../cocos2d-x/external/luaproxy/tolua/tolua_CCControl.h \
../cocos2d-x/external/luaproxy/tolua/tolua_CCGLProgram.h \
../cocos2d-x/external/luaproxy/tolua/tolua_CCScrollView.h \
../cocos2d-x/external/luaproxy/tolua/tolua_CCTableView.h \
../cocos2d-x/external/luaproxy/tolua/tolua_CursorTextField.h \
../cocos2d-x/external/luaproxy/tolua/tolua_LuaProxy.h \
../cocos2d-x/external/luaproxy/tolua/tolua_util.h \
../cocos2d-x/external/luaproxy/ui/CursorTextField.h \
../cocos2d-x/external/luaproxy/ui/UIUtil.h


INCLUDEPATH += \
../cocos2d-x/external/chipmunk \
../cocos2d-x/external/chipmunk/cocos2dx_support \
../cocos2d-x/external/chipmunk/include \
../cocos2d-x/external/chipmunk/include/constraints \
../cocos2d-x/external/chipmunk/luabinding \
../cocos2d-x/external/chipmunk/src \
../cocos2d-x/external/chipmunk/src/constraints \
../cocos2d-x/external/extra \
../cocos2d-x/external/extra/crypto \
../cocos2d-x/external/extra/crypto/base64 \
../cocos2d-x/external/extra/crypto/md5 \
../cocos2d-x/external/extra/crypto/xxtea \
../cocos2d-x/external/extra/luabinding \
../cocos2d-x/external/extra/native \
../cocos2d-x/external/extra/network \
../cocos2d-x/external/extra/platform \
../cocos2d-x/external/extra/platform/android \
../cocos2d-x/external/extra/platform/ios \
../cocos2d-x/external/extra/platform/ios/json \
../cocos2d-x/external/extra/platform/ios/openudid \
../cocos2d-x/external/extra/platform/ios_mac \
../cocos2d-x/external/extra/platform/mac \
../cocos2d-x/external/extra/platform/mac/openudid \
../cocos2d-x/external/extra/platform/win32 \
../cocos2d-x/external/extra/store \
../cocos2d-x/external/libwebsockets \
../cocos2d-x/external/libwebsockets/android \
../cocos2d-x/external/libwebsockets/android/include \
../cocos2d-x/external/libwebsockets/android/lib \
../cocos2d-x/external/libwebsockets/android/lib/armeabi \
../cocos2d-x/external/libwebsockets/android/lib/armeabi-v7a \
../cocos2d-x/external/libwebsockets/android/lib/x86 \
../cocos2d-x/external/libwebsockets/ios \
../cocos2d-x/external/libwebsockets/ios/include \
../cocos2d-x/external/libwebsockets/ios/lib \
../cocos2d-x/external/libwebsockets/mac \
../cocos2d-x/external/libwebsockets/mac/include \
../cocos2d-x/external/libwebsockets/mac/lib \
../cocos2d-x/external/libwebsockets/win32 \
../cocos2d-x/external/libwebsockets/win32/include \
../cocos2d-x/external/libwebsockets/win32/include/win32helpers \
../cocos2d-x/external/libwebsockets/win32/lib \
../cocos2d-x/external/luaproxy \
../cocos2d-x/external/luaproxy/tolua \
../cocos2d-x/external/luaproxy/ui
