
SOURCES += \
../cocos2d-x/extensions/AssetsManager/AssetsManager.cpp \
../cocos2d-x/extensions/CCArmature/animation/CCArmatureAnimation.cpp \
../cocos2d-x/extensions/CCArmature/animation/CCProcessBase.cpp \
../cocos2d-x/extensions/CCArmature/animation/CCTween.cpp \
../cocos2d-x/extensions/CCArmature/CCArmature.cpp \
../cocos2d-x/extensions/CCArmature/CCBone.cpp \
../cocos2d-x/extensions/CCArmature/datas/CCDatas.cpp \
../cocos2d-x/extensions/CCArmature/display/CCBatchNode.cpp \
../cocos2d-x/extensions/CCArmature/display/CCDecorativeDisplay.cpp \
../cocos2d-x/extensions/CCArmature/display/CCDisplayFactory.cpp \
../cocos2d-x/extensions/CCArmature/display/CCDisplayManager.cpp \
../cocos2d-x/extensions/CCArmature/display/CCShaderNode.cpp \
../cocos2d-x/extensions/CCArmature/display/CCSkin.cpp \
../cocos2d-x/extensions/CCArmature/external_tool/CCTexture2DMutable.cpp \
../cocos2d-x/extensions/CCArmature/external_tool/Json/CSContentJsonDictionary.cpp \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/json_reader.cpp \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/json_value.cpp \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/json_writer.cpp \
../cocos2d-x/extensions/CCArmature/utils/CCArmatureDataManager.cpp \
../cocos2d-x/extensions/CCArmature/utils/CCDataReaderHelper.cpp \
../cocos2d-x/extensions/CCArmature/utils/CCSpriteFrameCacheHelper.cpp \
../cocos2d-x/extensions/CCArmature/utils/CCTransformHelp.cpp \
../cocos2d-x/extensions/CCArmature/utils/CCTweenFunction.cpp \
../cocos2d-x/extensions/CCArmature/utils/CCUtilMath.cpp \
../cocos2d-x/extensions/CCBReader/CCBAnimationManager.cpp \
../cocos2d-x/extensions/CCBReader/CCBFileLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCBKeyframe.cpp \
../cocos2d-x/extensions/CCBReader/CCBReader.cpp \
../cocos2d-x/extensions/CCBReader/CCBSequence.cpp \
../cocos2d-x/extensions/CCBReader/CCBSequenceProperty.cpp \
../cocos2d-x/extensions/CCBReader/CCBValue.cpp \
../cocos2d-x/extensions/CCBReader/CCControlButtonLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCControlLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCData.cpp \
../cocos2d-x/extensions/CCBReader/CCLabelBMFontLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCLabelTTFLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCLayerColorLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCLayerGradientLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCLayerLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCMenuItemImageLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCMenuItemLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCNode+CCBRelativePositioning.cpp \
../cocos2d-x/extensions/CCBReader/CCNodeLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCNodeLoaderLibrary.cpp \
../cocos2d-x/extensions/CCBReader/CCParticleSystemQuadLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCScale9SpriteLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCScrollViewLoader.cpp \
../cocos2d-x/extensions/CCBReader/CCSpriteLoader.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControl.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlButton.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlColourPicker.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlHuePicker.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlPotentiometer.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlSaturationBrightnessPicker.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlSlider.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlStepper.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlSwitch.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlUtils.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCInvocation.cpp \
../cocos2d-x/extensions/GUI/CCControlExtension/CCScale9Sprite.cpp \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBox.cpp \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplAndroid.cpp \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplNone.cpp \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplWin.cpp \
../cocos2d-x/extensions/GUI/CCScrollView/CCScrollView.cpp \
../cocos2d-x/extensions/GUI/CCScrollView/CCSorting.cpp \
../cocos2d-x/extensions/GUI/CCScrollView/CCTableView.cpp \
../cocos2d-x/extensions/GUI/CCScrollView/CCTableViewCell.cpp \
../cocos2d-x/extensions/network/WebSocket.cpp


HEADERS += \
../cocos2d-x/extensions/cocos-ext.h \
../cocos2d-x/extensions/ExtensionMacros.h \
../cocos2d-x/extensions/AssetsManager/AssetsManager.h \
../cocos2d-x/extensions/CCArmature/animation/CCArmatureAnimation.h \
../cocos2d-x/extensions/CCArmature/animation/CCProcessBase.h \
../cocos2d-x/extensions/CCArmature/animation/CCTween.h \
../cocos2d-x/extensions/CCArmature/CCArmature.h \
../cocos2d-x/extensions/CCArmature/CCBone.h \
../cocos2d-x/extensions/CCArmature/datas/CCDatas.h \
../cocos2d-x/extensions/CCArmature/display/CCBatchNode.h \
../cocos2d-x/extensions/CCArmature/display/CCDecorativeDisplay.h \
../cocos2d-x/extensions/CCArmature/display/CCDisplayFactory.h \
../cocos2d-x/extensions/CCArmature/display/CCDisplayManager.h \
../cocos2d-x/extensions/CCArmature/display/CCShaderNode.h \
../cocos2d-x/extensions/CCArmature/display/CCSkin.h \
../cocos2d-x/extensions/CCArmature/external_tool/CCTexture2DMutable.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/CSContentJsonDictionary.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/autolink.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/config.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/features.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/forwards.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/json_batchallocator.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/json_lib.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/json_tool.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/reader.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/value.h \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json/writer.h \
../cocos2d-x/extensions/CCArmature/utils/CCArmatureDataManager.h \
../cocos2d-x/extensions/CCArmature/utils/CCArmatureDefine.h \
../cocos2d-x/extensions/CCArmature/utils/CCConstValue.h \
../cocos2d-x/extensions/CCArmature/utils/CCDataReaderHelper.h \
../cocos2d-x/extensions/CCArmature/utils/CCSpriteFrameCacheHelper.h \
../cocos2d-x/extensions/CCArmature/utils/CCTransformHelp.h \
../cocos2d-x/extensions/CCArmature/utils/CCTweenFunction.h \
../cocos2d-x/extensions/CCArmature/utils/CCUtilMath.h \
../cocos2d-x/extensions/CCBReader/CCBAnimationManager.h \
../cocos2d-x/extensions/CCBReader/CCBFileLoader.h \
../cocos2d-x/extensions/CCBReader/CCBKeyframe.h \
../cocos2d-x/extensions/CCBReader/CCBMemberVariableAssigner.h \
../cocos2d-x/extensions/CCBReader/CCBReader.h \
../cocos2d-x/extensions/CCBReader/CCBSelectorResolver.h \
../cocos2d-x/extensions/CCBReader/CCBSequence.h \
../cocos2d-x/extensions/CCBReader/CCBSequenceProperty.h \
../cocos2d-x/extensions/CCBReader/CCBValue.h \
../cocos2d-x/extensions/CCBReader/CCControlButtonLoader.h \
../cocos2d-x/extensions/CCBReader/CCControlLoader.h \
../cocos2d-x/extensions/CCBReader/CCData.h \
../cocos2d-x/extensions/CCBReader/CCLabelBMFontLoader.h \
../cocos2d-x/extensions/CCBReader/CCLabelTTFLoader.h \
../cocos2d-x/extensions/CCBReader/CCLayerColorLoader.h \
../cocos2d-x/extensions/CCBReader/CCLayerGradientLoader.h \
../cocos2d-x/extensions/CCBReader/CCLayerLoader.h \
../cocos2d-x/extensions/CCBReader/CCMenuItemImageLoader.h \
../cocos2d-x/extensions/CCBReader/CCMenuItemLoader.h \
../cocos2d-x/extensions/CCBReader/CCMenuLoader.h \
../cocos2d-x/extensions/CCBReader/CCNode+CCBRelativePositioning.h \
../cocos2d-x/extensions/CCBReader/CCNodeLoader.h \
../cocos2d-x/extensions/CCBReader/CCNodeLoaderLibrary.h \
../cocos2d-x/extensions/CCBReader/CCNodeLoaderListener.h \
../cocos2d-x/extensions/CCBReader/CCParticleSystemQuadLoader.h \
../cocos2d-x/extensions/CCBReader/CCScale9SpriteLoader.h \
../cocos2d-x/extensions/CCBReader/CCScrollViewLoader.h \
../cocos2d-x/extensions/CCBReader/CCSpriteLoader.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControl.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlButton.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlColourPicker.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlExtensions.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlHuePicker.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlPotentiometer.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlSaturationBrightnessPicker.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlSlider.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlStepper.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlSwitch.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCControlUtils.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCInvocation.h \
../cocos2d-x/extensions/GUI/CCControlExtension/CCScale9Sprite.h \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBox.h \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImpl.h \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplAndroid.h \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplIOS.h \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplMac.h \
../cocos2d-x/extensions/GUI/CCEditBox/CCEditBoxImplWin.h \
../cocos2d-x/extensions/GUI/CCScrollView/CCScrollView.h \
../cocos2d-x/extensions/GUI/CCScrollView/CCSorting.h \
../cocos2d-x/extensions/GUI/CCScrollView/CCTableView.h \
../cocos2d-x/extensions/GUI/CCScrollView/CCTableViewCell.h \
../cocos2d-x/extensions/network/WebSocket.h

INCLUDEPATH += \
../cocos2d-x/extensions \
../cocos2d-x/extensions/AssetsManager \
../cocos2d-x/extensions/CCArmature \
../cocos2d-x/extensions/CCArmature/animation \
../cocos2d-x/extensions/CCArmature/datas \
../cocos2d-x/extensions/CCArmature/display \
../cocos2d-x/extensions/CCArmature/external_tool \
../cocos2d-x/extensions/CCArmature/external_tool/Json \
../cocos2d-x/extensions/CCArmature/external_tool/Json/lib_json \
../cocos2d-x/extensions/CCArmature/utils \
../cocos2d-x/extensions/CCBReader \
../cocos2d-x/extensions/GUI \
../cocos2d-x/extensions/GUI/CCControlExtension \
../cocos2d-x/extensions/GUI/CCEditBox \
../cocos2d-x/extensions/GUI/CCScrollView \
../cocos2d-x/extensions/network

macx {
    INCLUDEPATH += \
    ../cocos2d-x/external/libwebsockets/mac/include
}
